import type { UserRole } from "@/dashboards/shared/types/roles";
import type { DashboardModule } from "./dashboardModules";

import {
  DASHBOARD_ACTIONS,
  type DashboardAction,
} from "./dashboardPermissions";

export type ModulePermissions = Partial<
  Record<DashboardModule, DashboardAction[]>
>;

export const DASHBOARD_ROLE_PERMISSIONS: Record<
  UserRole,
  ModulePermissions
> = {
  SUPER_ADMIN: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    TENANT_APPLICATIONS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.REVIEW,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
    ],

    SACCOS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
    ],

    USERS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
      DASHBOARD_ACTIONS.SUSPEND,
      DASHBOARD_ACTIONS.ACTIVATE,
    ],

    REGISTRATION_REQUESTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.REVIEW,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
      DASHBOARD_ACTIONS.SUSPEND,
      DASHBOARD_ACTIONS.ACTIVATE,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
      DASHBOARD_ACTIONS.ASSIGN,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    ROUTES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
    ],

    STAGES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
    ],

    STAGE_ASSIGNMENTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.DELETE,
      DASHBOARD_ACTIONS.ASSIGN,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    ARRIVALS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    QUEUE: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PLATFORM_CHARGES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  SACCO_ADMIN: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    USERS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.SUSPEND,
      DASHBOARD_ACTIONS.ACTIVATE,
    ],

    REGISTRATION_REQUESTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.REVIEW,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
      DASHBOARD_ACTIONS.SUSPEND,
      DASHBOARD_ACTIONS.ACTIVATE,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.ASSIGN,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    ROUTES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    STAGES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    STAGE_ASSIGNMENTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.ASSIGN,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    ARRIVALS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    QUEUE: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PLATFORM_CHARGES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  DIRECTOR: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    SACCOS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    USERS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.SUSPEND,
      DASHBOARD_ACTIONS.ACTIVATE,
    ],

    REGISTRATION_REQUESTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.REVIEW,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    ROUTES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    STAGES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    STAGE_ASSIGNMENTS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    ARRIVALS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    QUEUE: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PLATFORM_CHARGES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  MANAGER: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    USERS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    REGISTRATION_REQUESTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.REVIEW,
      DASHBOARD_ACTIONS.APPROVE,
      DASHBOARD_ACTIONS.REJECT,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
      DASHBOARD_ACTIONS.REVIEW,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.ASSIGN,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    ROUTES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    STAGES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    STAGE_ASSIGNMENTS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.ASSIGN,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    ARRIVALS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    QUEUE: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  STAGE_MARSHAL: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    ARRIVALS: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
    ],

    QUEUE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.REMOVE,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.DISPATCH,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  VEHICLE_OWNER: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.CREATE,
      DASHBOARD_ACTIONS.UPDATE,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  DRIVER: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    ROUTES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },

  CONDUCTOR: {
    OVERVIEW: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    FLEET: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    VEHICLE_CREWS: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    ROUTES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    DISPATCHES: [
      DASHBOARD_ACTIONS.VIEW,
    ],

    PROFILE: [
      DASHBOARD_ACTIONS.VIEW,
      DASHBOARD_ACTIONS.UPDATE,
    ],
  },
};