export const DASHBOARD_MODULES = {
  OVERVIEW: "OVERVIEW",

  TENANT_APPLICATIONS: "TENANT_APPLICATIONS",
  SACCOS: "SACCOS",

  USERS: "USERS",
  REGISTRATION_REQUESTS: "REGISTRATION_REQUESTS",

  FLEET: "FLEET",
  VEHICLE_OWNERS: "VEHICLE_OWNERS",
  VEHICLE_CREWS: "VEHICLE_CREWS",

  ROUTES: "ROUTES",
  STAGES: "STAGES",
  STAGE_ASSIGNMENTS: "STAGE_ASSIGNMENTS",

  QUEUE: "QUEUE",
  ARRIVALS: "ARRIVALS",
  DISPATCHES: "DISPATCHES",

  PLATFORM_CHARGES: "PLATFORM_CHARGES",

  PROFILE: "PROFILE",
  SETTINGS: "SETTINGS",
} as const;

export type DashboardModule =
  (typeof DASHBOARD_MODULES)[keyof typeof DASHBOARD_MODULES];